version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gewuser
      POSTGRES_PASSWORD: gewpass
      POSTGRES_DB: gewdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data: